name: .NET Desktop Build
on:
  workflow_dispatch
jobs:
  build:
    strategy:
      matrix:
        configuration: [Release]
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.3.1

    - name: Setup Nuget
      uses: NuGet/setup-nuget@v1.2.0

    - name: Restore Nuget Packages
      run: nuget restore StrPrsL.sln

    - name: Build Solution
      run: dotnet publish StrPrsL.sln -c Release -a x86 -p:PublishSingleFile=true -p:SelfContained=true -p:PublishReadyToRun=false

    - name: Current Directory
      run: dir

    - name: Debug Files
      run: ls -r

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: StrPrsL
        path: StrPrsL\bin\Release\net6.0-windows\win-x86\publish\StrPrsL.exe

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: StrPrsL

      - name: Current Directory
        run: dir

      - name: Debug Files
        run: ls -r

      - name: Release
        uses: ncipollo/release-action@v1.13.0
        with:
          tag: v-CI-${{ github.run_number }}
          name: Release ${{ github.run_number }}
          commit: main
          draft: true
          generateReleaseNotes: true
          makeLatest: true
          artifacts: "StrPrsL.exe"
